#!/usr/bin/env python
# Created on May 27, 2012
# @author: Elliott L. Barcikowski
'''Quick script to dump the info about all the electrodes found in the specified
.nev files.  This script dumps to the console the results of all the pyns  
versions of the Neuroshare API functions of the type ns_GetFileInfo, 
ns_GetEntityInfo, etc. 
'''
from optparse import OptionParser
from pyns.nsfile import NSFile
from pyns.nsentity import EntityType

import sys
import Tkinter, tkFileDialog # if no file is specified, open a simple dialog

if __name__ == '__main__':
    parser = OptionParser(usage="usage: %prog [OPTIONS..] [NEV_INPUT_FILE]")
    parser.add_option("-s", "--single", dest="single", default=False,
                      action="store_true", help="Only open single specified file")
    parser.add_option("-k", "--skip", dest="skip", default=0,
                      help="Skip the first SKIP entities", type=int)
    parser.add_option("-e", "--entity", dest="entity",help="only show entities of "\
                      "type ENTITY (analog, segment, event, neural)", default=None)
    
    (options, args) = parser.parse_args()
    # check that we have an input file and that it opens successfully  
    if len(args) == 0:
        # if no file is specified, we'll open a simple tk file dialog and
        # and have the user specify a file
        root = Tkinter.Tk()
        root.withdraw()
        nev_formats = [ ("NEV", "*.nev"), ("NSX", "*.ns?") ]
        filename = tkFileDialog.askopenfilename(title="Choose a file",
                                                filetypes=nev_formats)
    else:
        filename = args[0]
    nsfile = NSFile(filename, options.single)
    if nsfile == None:
        parser.error("failed to open file: {0:s}".format(args[0])) 
    # check that entity option is okay
    want_entity = None 
    if options.entity != None:
        entity_strings = [EntityType.get_entity_string(eid) for eid in range(0, 4)]
        if not options.entity in entity_strings:
            parser.error("invalid entity: {0:s}".format(options.entity))
        else:
            want_entity = EntityType.get_entity_id(options.entity)            
    # NSFile.get_file_info() is the equivalent of the Neuroshare API function ns_GetFileInfo  
    info = nsfile.get_file_info()
    print info
    for entity in nsfile.entities[options.skip:]:
        # if we are using the want entity option.  Check entity type and 
        # skip if we don't have the kind that we want
        if want_entity != None:
            if entity.entity_type != want_entity:
                continue
        # pyns.Entity.get_entity_info is the equivalent of the Neuroshare 
        # function ns_GetEntityInfo
        print entity.get_entity_info()
        if entity.entity_type == EntityType.segment:
            # pyns.SegmentEntity.get_segment_info is the equivalent of the Neuroshare
            # function ns_GetSegmentInfo            
            print entity.get_segment_info()
        elif entity.entity_type == EntityType.analog:
            # pyns.AnalogEntity.get_analog_info is the equivalent of the Neuroshare
            # function ns_GetAnalogInfo            
            print entity.get_analog_info()
        elif entity.entity_type == EntityType.neural:
            # pyns.Neural.get_neural_info is the equivalent of the Neuroshare
            # function ns_GetNeuralInfo            
            print entity.get_neural_info()
        elif entity.entity_type == EntityType.event:
            # pyns.Neural.get_neural_info is the equivalent of the Neuroshare
            # function ns_GetNeuralInfo            
            print entity.get_event_info()
        else:
            sys.stderr.write("warning: invalid entity type: {0:d}\n".format(entity.entity_type))
        