#!/usr/bin/env python
# Created on May 27, 2012
# @author: Elliott L. Barcikowski
'''Quick script to dump the contents of headers and extended headers in NEV and 
and NSx files for debugging purposes.
'''
from optparse import OptionParser
from pyns.nsparser import ParserFactory

import os
from glob import glob
import Tkinter, tkFileDialog # if no file is specified, open a simple dialog

def dump_namedtuple(ntuple, use_full=False):
    for key, value in ntuple.__dict__.iteritems():
        if type(value) == str:
            if use_full:
                print "{0}={1:s},".format(key, repr(value)),
            else:            
                print "{0}={1:s},".format(key, value.split('\0')[0]),
        else:
            print "{0}={1},".format(key, value),
    print 

if __name__ == '__main__':
    parser = OptionParser(usage="usage: %prog [OPTIONS..] [NEV_INPUT_FILE]")
    parser.add_option("-s", "--single", dest="single", default=False,
                      action="store_true", help="Only open single specified file")
    parser.add_option("-f", "--full", dest="full", default=False,
                      action="store_true", help="For string fields, show all characters")    
    
    (options, args) = parser.parse_args()
    # check that we have an input file and that it opens successfully  
    if len(args) == 0:
        # if no file is specified, we'll open a simple tk file dialog and
        # and have the user specify a file
        root = Tkinter.Tk()
        root.withdraw()
        nev_formats = [ ("NEV", "*.nev"), ("NSX", "*.ns?") ]
        filename = tkFileDialog.askopenfilename(title="Choose a file",
                                                filetypes=nev_formats)
    else:
        filename = args[0]
    if options.single:
        file_list = [filename]
    else:
        nsx_files = glob(filename[:-4] + '.ns[1-9]')
        file_list = glob(filename[:-4] + '.nev') + nsx_files
    
    for input_file in file_list:
        parser = ParserFactory(input_file)
        print "Found {0:s} file: {1:s}".format(parser.file_type, 
                                               os.path.basename(input_file))
        dump_namedtuple(parser.get_basic_header())
        if parser.file_type == "NEURALEV" or parser.file_type == "NEURALCD":
            for ext_header in parser.get_extended_headers():
                dump_namedtuple(ext_header, options.full)
            